port: 4222

jetstream {
    store_dir: "./jetstream"
}

authorization {
    users = [
        {
            user: "user-service"
            password: "YOUR_PASSWORD"

            permissions {
                publish = [
                    "user.created",
                    "$JS.API.>"
                ]

                subscribe = [
                    "_INBOX.>"
                ]
            }
        },

        {
            user: "notification-service"
            password: "YOUR_PASSWORD"

            permissions {
                publish = [
                    "$JS.API.>",
                    "$JS.ACK.>"
                ]

                subscribe = [
                    "user.created",
                    "_INBOX.>"
                ]
            }
        }
    ]
}